---

- name: Install mariadb-server
  yum: 
    name: "{{ mariadb-server-version }}"
    state: present

- name: copy server.cnf template config
  template:
    src: etc/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644

- name: copy server.cnf template config
  template:
    src: etc/my.cnf.d/server.conf.j2
    dest: /etc/my.cnf.d/server.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure mariadb is started and enabled
  service:
    name: mariadb
    state: started
    enabled: yes

- name: create initial database
  mysql_db:
    name: {{ initial-db-name }}
    state: present
  when: create-initial-db == true  

- name: create initial user
  mysql_user:
    name: {{ initial-user-name }}
    password: {{ initial-user-pass }}
    host: {{ initial-user-host }}
    priv: '{{ initial-user-grants }}'
    state: present
  when: create-initial-user == true
